name: ci

on:
  push:
    branches:
      - master
  schedule:
    - cron: "*5-15 * * * *"

jobs:
  autogreen:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: auto green
        run: |
          git config --local user.email "lpy15231240@outlook.com"
          git config --local user.name "bushiwode"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git pull --rebase
          git commit --allow-empty -m "Make progress Every Day!"
          git push
